name: docker-test
on:
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: mcr.microsoft.com/azure-cli:2.8.0
